---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'

- name: ensure settings directory exists
  become: yes
  become_user: root
  file:
    path: '{{emacs_config_emacs_d}}'
    state: directory
    mode: 0755

- name: install emacs modes/settings
  become : yes
  become_user: root
  with_items:
    - f: 48snippets.el
    - f: 49myemacs.el
    - f: 50melpa.el
    - f: 50mycpp.el
    - f: 50js.el
    - f: 50python.el
    - f: 51fixssh.el
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d|default(emacs_config_emacs_d)}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'

- name: bootstrap root user install...
  become: yes
  become_user: root
  command: emacs --batch
