---
- name: install spacemacs
  git:
    repo: 'https://github.com/syl20bnr/spacemacs.git'
    dest: '{{ emacs_config_dotemacs_d  }}'
- name: install .spacemacs
  template:
    src: .spacemacs.j2
    dest: '{{ emacs_config_dotspacemacs }}'

- name: bootstrap install...
  command: emacs --batch
