---
- name: install emacs modes/settings
  become : yes
  become_user: root
  with_items:
    - 49myemacs.el
    - 50melpa.el
    - 50mycpp.el
    - 50python.el
    - 51dockertramp.el
  template: >
    src={{item}}.j2
    dest={{emacs_modes_dir}}/{{item}}
    mode=0644

- name: bootstrap root user install...
  become: yes
  become_user: root
  command: emacs --batch
