---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: install emacs modes/settings
  become : yes
  become_user: root
  with_items:
    - 49myemacs.el
    - 50melpa.el
    - 50mycpp.el
    - 50python.el
    - 51dockertramp.el
  template: >
    src={{item}}.j2
    dest={{emacs_modes_dir}}/{{item}}
    mode=0644

- name: bootstrap root user install...
  become: yes
  become_user: root
  command: emacs --batch
